name: woocommerce_api
description: A package to interact with the WooCommerce API.
version: 0.0.9
author: Samarth Agarwal <samarthagarwal@live.com>
homepage: https://github.com/samarthagarwal/woocommerce_dart

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.3
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

environment:
  sdk: ">=2.6.0 <3.0.0"